# Generated by Django 6.1.1 on 2026-09-12 08:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statutory_citations', models.TextField(blank=True, default='')),
                ('subject_en', models.CharField(blank=True, default='', max_length=255)),
                ('body_en', models.TextField(blank=True, default='')),
                ('body_ur', models.TextField(blank=True, default='')),
                ('official_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBuffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(choices=[('web', 'Web Portal'), ('whatsapp', 'WhatsApp')], default='web', max_length=20)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='complaints/images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='complaints/audio/')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('landmark_hint', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued in Redis'), ('PROCESSING', 'AI Inference in Progress'), ('READY_FOR_REVIEW', 'Review Package Ready'), ('CONFIRMED', 'Confirmed by Citizen'), ('FAILED', 'Processing Failed')], default='QUEUED', max_length=20)),
                ('inferred_category', models.CharField(blank=True, max_length=100, null=True)),
                ('inferred_authority', models.CharField(blank=True, max_length=50, null=True)),
                ('inferred_severity', models.CharField(blank=True, max_length=10, null=True)),
                ('layman_summary', models.TextField(blank=True, null=True)),
                ('draft_subject_en', models.CharField(blank=True, max_length=255, null=True)),
                ('draft_body_en', models.TextField(blank=True, null=True)),
                ('draft_body_ur', models.TextField(blank=True, null=True)),
                ('statutory_citations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('target_authority', models.CharField(choices=[('KWSC', 'KW&SC'), ('KMC', 'KMC'), ('SSWMB', 'SSWMB'), ('CANTONMENT', 'Cantonment')], max_length=20)),
                ('issue_category', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('P0', 'P0 - Emergency / Critical Hazard'), ('P1', 'P1 - Major Disruption'), ('P2', 'P2 - Routine Maintenance')], default='P1', max_length=10)),
                ('official_status', models.CharField(choices=[('PENDING', 'Pending Department Action'), ('IN_PROGRESS', 'Crews Dispatched / In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('landmark', models.CharField(max_length=255)),
                ('community_reports_count', models.PositiveIntegerField(default=1)),
                ('first_reported_at', models.DateTimeField(auto_now_add=True)),
                ('last_reported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
