# Generated by Django 6.1.1 on 2026-09-17 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('COLLECTING', 'Collecting problem/location/photos'), ('AWAITING_CONFIRM_REPORT', 'Asked user: generate report now?'), ('AWAITING_SUBMIT', 'Report generated, asked user: submit?'), ('SUBMITTED', 'Submitted to DB'), ('DISCARDED', 'User started a new report, this one was dropped')], default='COLLECTING', max_length=30)),
                ('collected_texts', models.JSONField(blank=True, default=list)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('landmark_text', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_report', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ready_prompt_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.FileField(upload_to='conversation_images/')),
                ('extracted_info', models.TextField(blank=True, default='')),
                ('analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.conversationsession')),
            ],
        ),
    ]
