# Generated by Django 6.1.1 on 2026-09-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversationsession_sessionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdossier',
            name='raw_citizen_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sessionattachment',
            name='master_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.masterincident'),
        ),
    ]
